FROM node:16-alpine

FROM node:16-alpine AS builder

USER root
RUN mkdir -p /app
WORKDIR /app
RUN npm install libp2p-webrtc-star@0.22.3

FROM node:16-alpine

COPY --from=builder /app /app
WORKDIR /app
CMD npx star-signal
