FROM node:14-alpine AS builder

RUN apk update && apk add python make gcc g++

RUN mkdir -p /app
COPY ./ /app
WORKDIR /app

RUN npm install
RUN npm run tsc

FROM node:14-alpine

RUN mkdir -p /app
COPY --from=builder /app /app
WORKDIR /app

RUN npm link
CMD automerge-swarm-d
