# Double-check errors on each commit for main workspaces
# caching: https://github.com/actions/setup-node
name: check typescript
on:
  push:
  pull_request:
jobs:
  collabswarm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm tsc
  collabswarm-automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm-automerge tsc
  collabswarm-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm-react tsc
  collabswarm-redux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm-redux tsc
  collabswarm-yjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm-yjs tsc
