#  Double-check errors on each commit for main workspaces
name: check typescript
on:
  push:
  pull_request:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
  collabswarm:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn workspace @collabswarm/collabswarm doc
  collabswarm-automerge:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn workspace @collabswarm/collabswarm-automerge doc
  collabswarm-react:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn workspace @collabswarm/collabswarm-react doc
  collabswarm-redux:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn workspace @collabswarm/collabswarm-redux doc
  collabswarm-yjs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: yarn workspace @collabswarm/collabswarm-yjs doc
