# Confirm no typescript errors are introduced
# gh node yarn caching: https://github.com/actions/setup-node
# tsc 3.0 build mode: https://www.typescriptlang.org/docs/handbook/project-references.html#build-mode-for-typescript

name: tsc
on:
  push:
    branches-ignore:
      - docs
jobs:
  collabswarm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: nodeversion
        run: echo "version=$(grep nodejs .tool-versions | sed -e 's/[^[:space:]]*[[:space:]]*//')" >> $GITHUB_OUTPUT
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nodeversion.outputs.version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm tsc
  collabswarm-automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: nodeversion
        run: echo "version=$(grep nodejs .tool-versions | sed -e 's/[^[:space:]]*[[:space:]]*//')" >> $GITHUB_OUTPUT
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nodeversion.outputs.version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm-automerge tsc
  collabswarm-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: nodeversion
        run: echo "version=$(grep nodejs .tool-versions | sed -e 's/[^[:space:]]*[[:space:]]*//')" >> $GITHUB_OUTPUT
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nodeversion.outputs.version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm-react tsc
  collabswarm-redux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: nodeversion
        run: echo "version=$(grep nodejs .tool-versions | sed -e 's/[^[:space:]]*[[:space:]]*//')" >> $GITHUB_OUTPUT
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nodeversion.outputs.version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm-redux tsc
  collabswarm-yjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: nodeversion
        run: echo "version=$(grep nodejs .tool-versions | sed -e 's/[^[:space:]]*[[:space:]]*//')" >> $GITHUB_OUTPUT
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nodeversion.outputs.version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn workspace @collabswarm/collabswarm-yjs tsc
